hostname spine1
password zebra
enable password zebra

interface eth1
 ip address 10.0.0.0/31
exit

interface eth2
 ip address 10.0.0.2/31
exit

interface lo
 ip address 1.1.1.1/32
exit

router ospf
 ospf router-id 1.1.1.1
 network 10.0.0.0/31 area 0
 network 10.0.0.2/31 area 0
 network 1.1.1.1/32 area 0
exit

line vty

