hostname spine1
password zebra
enable password zebra

interface eth1
 ip address 10.0.0.0/31
exit

interface eth2
 ip address 10.0.0.2/31
exit

interface lo
 ip address 1.1.1.1/32
exit

router bgp 65000
 bgp router-id 1.1.1.1
 neighbor 11.11.11.11 remote-as 65000
 neighbor 11.11.11.11 update-source lo
 neighbor 22.22.22.22 remote-as 65000
 neighbor 22.22.22.22 update-source lo
 !
 address-family l2vpn evpn
  neighbor 11.11.11.11 activate
  neighbor 11.11.11.11 route-reflector-client
  neighbor 22.22.22.22 activate
  neighbor 22.22.22.22 route-reflector-client
 exit-address-family
exit

router ospf
 ospf router-id 1.1.1.1
 network 1.1.1.1/32 area 0
 network 10.0.0.0/31 area 0
 network 10.0.0.2/31 area 0
exit

line vty
